"""empty message

Revision ID: 49b3630bb8f2
Revises: 56a25be4683d
Create Date: 2023-04-07 16:36:22.311611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b3630bb8f2'
down_revision = '56a25be4683d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_going', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_events', schema=None) as batch_op:
        batch_op.drop_column('is_going')

    # ### end Alembic commands ###
