"""empty message

Revision ID: 8b258d83710e
Revises: fd654645c215
Create Date: 2023-04-19 06:15:26.185978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b258d83710e'
down_revision = 'fd654645c215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_followers_profile_id_profile'), 'profile', ['profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_followers_profile_id_profile'), type_='foreignkey')
        batch_op.drop_column('profile_id')

    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='fk_chats_receiver_id_users'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='fk_chats_sender_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
