"""empty message

Revision ID: b0081d3b1c2d
Revises: 8b258d83710e
Create Date: 2023-04-20 07:16:13.099940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0081d3b1c2d'
down_revision = '8b258d83710e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_following', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_column('is_following')

    # ### end Alembic commands ###
